#!/bin/sh
set -eu

: "${PATENTAGILITY_WEB_WORKERS:=1}"
: "${PATENTAGILITY_WEB_THREADS:=64}"
: "${PATENTAGILITY_MODEL_PROFILE:=throughput}"
: "${PATENTAGILITY_DEVICE:=cpu}"

export PATENTAGILITY_WEB_WORKERS
export PATENTAGILITY_WEB_THREADS
export PATENTAGILITY_MODEL_PROFILE
export PATENTAGILITY_DEVICE

exec uv run gunicorn -c gunicorn.conf.py
